import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/auth';
import { showSuccessToast, showErrorToast, logError } from '@/utils/errorHandling';
import type { Location, LocationFormData, LocationFilters } from '@/types/location';

export const useLocations = (filters?: LocationFilters) => {
  const { userProfile } = useAuth();

  return useQuery({
    queryKey: ['locations', filters],
    queryFn: async () => {
      if (!userProfile?.tenant_id) {
        throw new Error('No tenant found');
      }

      let query = supabase
        .from('locations')
      .select(`
        *,
        department:department_id(id, name),
        location_level_data:location_level_id(id, name, code, is_active)
      `)
        .eq('tenant_id', userProfile.tenant_id)
        .order('name', { ascending: true });

      // Apply search filter
      if (filters?.search) {
        query = query.or(`name.ilike.%${filters.search}%,location_code.ilike.%${filters.search}%`);
      }

      // Apply department filter
      if (filters?.department_id) {
        query = query.eq('department_id', filters.department_id);
      }

      // Apply location level filter
      if (filters?.location_level_id) {
        query = query.eq('location_level_id', filters.location_level_id);
      }

      const { data, error } = await query;

      if (error) throw error;

      return data as Location[];
    },
    enabled: !!userProfile?.tenant_id,
  });
};

export const useCreateLocation = () => {
  const queryClient = useQueryClient();
  const { userProfile } = useAuth();

  return useMutation({
    mutationFn: async (data: LocationFormData) => {
      if (!userProfile?.tenant_id) {
        throw new Error('User not authenticated');
      }

      const locationData = {
        name: data.name,
        description: data.description,
        tenant_id: userProfile.tenant_id,
        department_id: data.department_id || null,
        location_level_id: data.location_level_id,
        // location_code will be auto-generated by the database trigger if not provided
        ...(data.location_code && { location_code: data.location_code }),
      };

      const { data: result, error } = await supabase
        .from('locations')
        .insert(locationData)
        .select()
        .single();

      if (error) throw error;

      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['locations'] });
      showSuccessToast("Location created successfully");
    },
    onError: (error) => {
      showErrorToast(error, { title: 'Create Failed', context: 'Location' });
    },
  });
};

export const useUpdateLocation = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<LocationFormData> }) => {
      const { data: result, error } = await supabase
        .from('locations')
        .update(data)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;

      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['locations'] });
      showSuccessToast("Location updated successfully");
    },
    onError: (error) => {
      showErrorToast(error, { title: 'Update Failed', context: 'Location' });
    },
  });
};

export const useDeleteLocation = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('locations')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['locations'] });
      showSuccessToast("Location deleted successfully");
    },
    onError: (error) => {
      showErrorToast(error, { title: 'Delete Failed', context: 'Location' });
    },
  });
};
