
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/auth';
import { toast } from '@/components/ui/use-toast';
import type { WorkOrder, WorkOrderFormData, WorkOrderFilters } from '@/types/workOrder';

export const useWorkOrders = (filters?: WorkOrderFilters) => {
  const { userProfile } = useAuth();

  return useQuery({
    queryKey: ['work-orders', filters],
    queryFn: async () => {
      if (!userProfile?.tenant_id) {
        throw new Error('No tenant found');
      }

      // Log tenant ID being used for filtering
      console.log('🔍 DEBUG: Fetching work orders for tenant:', userProfile.tenant_id);
      console.log('🔍 DEBUG: Applied filters:', filters);

      let query = supabase
        .from('work_orders')
        .select(`
          *,
          asset:assets(name),
          assigned_user:users!assigned_to(name),
          created_user:users!created_by(name)
        `)
        .eq('tenant_id', userProfile.tenant_id)
        .order('work_order_number', { ascending: false });

      // Apply filters
      if (filters?.status) {
        query = query.eq('status', filters.status);
      }
      if (filters?.priority) {
        query = query.eq('priority', filters.priority);
      }
      if (filters?.work_type) {
        query = query.eq('work_type', filters.work_type);
      }
      if (filters?.assigned_to) {
        query = query.eq('assigned_to', filters.assigned_to);
      }
      if (filters?.asset_id) {
        query = query.eq('asset_id', filters.asset_id);
      }
      if (filters?.search) {
        query = query.or(`title.ilike.%${filters.search}%,description.ilike.%${filters.search}%`);
      }

      const { data, error } = await query;

      if (error) {
        console.error('Error fetching work orders:', error);
        throw error;
      }

      // Log detailed results for debugging
      console.log('🔍 DEBUG: Total work orders fetched:', data?.length || 0);
      if (data && data.length > 0) {
        const statusCounts = data.reduce((acc, wo) => {
          acc[wo.status] = (acc[wo.status] || 0) + 1;
          return acc;
        }, {} as Record<string, number>);
        console.log('🔍 DEBUG: Status breakdown:', statusCounts);
        console.log('🔍 DEBUG: First few work orders:', data.slice(0, 3).map(wo => ({
          id: wo.id,
          work_order_number: wo.work_order_number,
          title: wo.title,
          status: wo.status,
          priority: wo.priority
        })));
      } else {
        console.log('🔍 DEBUG: No work orders found with current filters');
      }

      return data as WorkOrder[];
    },
    enabled: !!userProfile?.tenant_id,
  });
};

export const useCreateWorkOrder = () => {
  const queryClient = useQueryClient();
  const { userProfile } = useAuth();

  return useMutation({
    mutationFn: async (data: WorkOrderFormData) => {
      if (!userProfile?.tenant_id || !userProfile?.id) {
        throw new Error('User not authenticated');
      }

      // Remove work_order_number from the data as it will be auto-generated by the trigger
      const { work_order_number, ...dataWithoutWorkOrderNumber } = data;
      
      const workOrderData = {
        ...dataWithoutWorkOrderNumber,
        tenant_id: userProfile.tenant_id,
        created_by: userProfile.id,
        estimated_hours: data.estimated_hours ? parseFloat(data.estimated_hours) : null,
        estimated_cost: data.estimated_cost ? parseFloat(data.estimated_cost) : null,
      };

      const { data: result, error } = await supabase
        .from('work_orders')
        .insert(workOrderData as any) // Type assertion to handle auto-generated work_order_number
        .select()
        .single();

      if (error) {
        console.error('Error creating work order:', error);
        throw error;
      }

      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      toast({
        title: "Success",
        description: "Work order created successfully",
      });
    },
    onError: (error: any) => {
      console.error('Create work order error:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to create work order",
        variant: "destructive",
      });
    },
  });
};

export const useUpdateWorkOrder = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<WorkOrderFormData> }) => {
      const updateData = {
        ...data,
        estimated_hours: data.estimated_hours ? parseFloat(data.estimated_hours) : null,
        estimated_cost: data.estimated_cost ? parseFloat(data.estimated_cost) : null,
      };

      const { data: result, error } = await supabase
        .from('work_orders')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) {
        console.error('Error updating work order:', error);
        throw error;
      }

      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      toast({
        title: "Success",
        description: "Work order updated successfully",
      });
    },
    onError: (error: any) => {
      console.error('Update work order error:', error);
      toast({
        title: "Error",
        description: error.message || "Failed to update work order",
        variant: "destructive",
      });
    },
  });
};
