import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/auth';
import { WorkRequest, WorkRequestCategory, WorkRequestFormData, WorkRequestFilters } from '@/types/workRequest';
import { useToast } from '@/hooks/use-toast';

// Fetch work request categories
export const useWorkRequestCategories = () => {
  return useQuery({
    queryKey: ['work-request-categories'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('work_request_categories')
        .select('*')
        .eq('is_active', true)
        .order('sort_order');
      
      if (error) throw error;
      return data as WorkRequestCategory[];
    },
  });
};

// Fetch current user's work requests
export const useMyWorkRequests = () => {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['my-work-requests', user?.id],
    queryFn: async () => {
      if (!user?.id) return [];
      
      const { data, error } = await supabase
        .from('work_requests')
        .select(`
          *,
          location:locations(name),
          work_order:work_orders(work_order_number)
        `)
        .eq('submitted_by', user.id)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as unknown as WorkRequest[];
    },
    enabled: !!user?.id,
  });
};

// Fetch all work requests (for admins)
export const useWorkRequests = (filters?: WorkRequestFilters) => {
  return useQuery({
    queryKey: ['work-requests', filters],
    queryFn: async () => {
      let query = supabase
        .from('work_requests')
        .select(`
          *,
          location:locations(name),
          work_order:work_orders(work_order_number),
          customer:customers(
            id, name, email, phone, phone_extension,
            department:departments(name),
            job_title:job_titles(title_name),
            work_area:locations(name),
            supervisor:customers!customers_reports_to_fkey(name)
          )
        `)
        .order('created_at', { ascending: false });
      
      if (filters?.status && filters.status !== 'all') {
        query = query.eq('status', filters.status);
      }
      if (filters?.category) {
        query = query.eq('category', filters.category);
      }
      if (filters?.dateFrom) {
        query = query.gte('created_at', filters.dateFrom.toISOString());
      }
      if (filters?.dateTo) {
        query = query.lte('created_at', filters.dateTo.toISOString());
      }
      
      const { data, error } = await query;
      
      if (error) throw error;
      
      // Fetch submitter and reviewer info separately
      if (data && data.length > 0) {
        const submitterIds = [...new Set(data.map(r => r.submitted_by))];
        const reviewerIds = [...new Set(data.filter(r => r.reviewed_by).map(r => r.reviewed_by!))];
        const allUserIds = [...new Set([...submitterIds, ...reviewerIds])];
        
        const { data: users } = await supabase
          .from('users')
          .select('id, name, email')
          .in('id', allUserIds);
        
        const userMap = new Map(users?.map(u => [u.id, u]) || []);
        
        return data.map(request => ({
          ...request,
          submitter: userMap.get(request.submitted_by) || null,
          reviewer: request.reviewed_by ? userMap.get(request.reviewed_by) || null : null,
        })) as unknown as WorkRequest[];
      }
      
      return data as unknown as WorkRequest[];
    },
  });
};

// Create a new work request
export const useCreateWorkRequest = () => {
  const queryClient = useQueryClient();
  const { user, userProfile } = useAuth();
  const { toast } = useToast();
  
  return useMutation({
    mutationFn: async (formData: WorkRequestFormData) => {
      if (!user?.id || !userProfile?.tenant_id) {
        throw new Error('User must be logged in');
      }
      
      const { data, error } = await supabase
        .from('work_requests')
        .insert({
          tenant_id: userProfile.tenant_id,
          submitted_by: formData.customer_id ? null : user.id,
          customer_id: formData.customer_id || null,
          title: formData.title,
          description: formData.description,
          category: formData.category,
          priority: formData.priority || 'medium',
          location_id: formData.location_id || null,
          location_description: formData.location_description || null,
          request_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['my-work-requests'] });
      queryClient.invalidateQueries({ queryKey: ['work-requests'] });
      toast({
        title: 'Request Submitted',
        description: 'Your work request has been submitted successfully.',
      });
    },
    onError: (error) => {
      toast({
        title: 'Error',
        description: `Failed to submit request: ${error.message}`,
        variant: 'destructive',
      });
    },
  });
};

// Update work request status
export const useUpdateWorkRequest = () => {
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const { toast } = useToast();
  
  return useMutation({
    mutationFn: async ({ 
      id, 
      status, 
      rejection_reason 
    }: { 
      id: string; 
      status: 'approved' | 'rejected'; 
      rejection_reason?: string;
    }) => {
      const { data, error } = await supabase
        .from('work_requests')
        .update({
          status,
          rejection_reason: rejection_reason || null,
          reviewed_by: user?.id,
          reviewed_at: new Date().toISOString(),
        })
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return data;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['work-requests'] });
      queryClient.invalidateQueries({ queryKey: ['my-work-requests'] });
      toast({
        title: variables.status === 'approved' ? 'Request Approved' : 'Request Rejected',
        description: `The work request has been ${variables.status}.`,
      });
    },
    onError: (error) => {
      toast({
        title: 'Error',
        description: `Failed to update request: ${error.message}`,
        variant: 'destructive',
      });
    },
  });
};

// Convert work request to work order
export const useConvertToWorkOrder = () => {
  const queryClient = useQueryClient();
  const { user, userProfile } = useAuth();
  const { toast } = useToast();
  
  return useMutation({
    mutationFn: async ({ 
      requestId,
      workOrderData 
    }: { 
      requestId: string;
      workOrderData: {
        title: string;
        description: string;
        priority: string;
        location_id?: string;
        assigned_to?: string;
      };
    }) => {
      if (!userProfile?.tenant_id || !user?.id) {
        throw new Error('User must be logged in');
      }
      
      // Create the work order
      const { data: workOrder, error: woError } = await supabase
        .from('work_orders')
        .insert({
          tenant_id: userProfile.tenant_id,
          title: workOrderData.title,
          description: workOrderData.description,
          priority: workOrderData.priority,
          location_id: workOrderData.location_id || null,
          assigned_to: workOrderData.assigned_to || null,
          status: 'Open',
          created_by: user.id,
          work_order_number: '', // Will be auto-generated
        })
        .select()
        .single();
      
      if (woError) throw woError;
      
      // Update the work request
      const { error: reqError } = await supabase
        .from('work_requests')
        .update({
          status: 'converted',
          work_order_id: workOrder.id,
          reviewed_by: user.id,
          reviewed_at: new Date().toISOString(),
        })
        .eq('id', requestId);
      
      if (reqError) throw reqError;
      
      return workOrder;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-requests'] });
      queryClient.invalidateQueries({ queryKey: ['my-work-requests'] });
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      toast({
        title: 'Work Order Created',
        description: 'The request has been converted to a work order.',
      });
    },
    onError: (error) => {
      toast({
        title: 'Error',
        description: `Failed to create work order: ${error.message}`,
        variant: 'destructive',
      });
    },
  });
};
