// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzpweuuvyuaawpttoqkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16cHdldXV2eXVhYXdwdHRvcWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTM4ODUsImV4cCI6MjA2NDg4OTg4NX0.7EbVEOq7uoOTMp2DpD5IdXVLR1uK6FcqVp1o2aP9NC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);